CREATE TABLE users (
   id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
   first_name VARCHAR(50),
   last_name VARCHAR(50),
   email VARCHAR(255) UNIQUE,
   email_verified_at TIMESTAMP NULL,
   phone_number VARCHAR(20),
   phone_verified_at TIMESTAMP NULL, -- Đã sửa từ VARCHAR sang TIMESTAMP
   avatar VARCHAR(255),
   background_profile VARCHAR(255),
   from_city_id INT NULL,
   current_city_id INT NULL,
   relationship_status INT NULL,
   gender TINYINT NOT NULL COMMENT '0:nữ, 1:nam, 2:khác',
   day_of_birth INT NULL,
   month_of_birth INT NULL,
   year_of_birth INT NULL,
   about_me VARCHAR(255),
   password VARCHAR(255) NOT NULL,
   latest_login_at TIMESTAMP NULL,
   latest_ip_login VARCHAR(255),
   last_activity_at TIMESTAMP NULL COMMENT 'Thời gian online cuối',
   status TINYINT DEFAULT 1,
   status_active TINYINT DEFAULT 0 COMMENT 'Trạng thái hoạt động',
   type_user TINYINT NOT NULL COMMENT 'học sinh, phụ huynh, nhà trường, admin',
   fcm_token VARCHAR(255),
   refresh_token VARCHAR(255),
   remember_token VARCHAR(100),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP NULL,

   FULLTEXT(first_name),
   FULLTEXT(last_name),
   INDEX idx_phone_number (phone_number),
   INDEX idx_name (first_name, last_name),
   INDEX idx_cities (from_city_id, current_city_id),
   INDEX idx_status (status, status_active),
   INDEX idx_dob (day_of_birth, month_of_birth, year_of_birth)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;